name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest  # Using Windows for System.Speech compatibility

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Using latest .NET version
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Check code formatting
      run: |
        dotnet format --verify-no-changes --verbosity diagnostic
        
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Check for compiler warnings
      run: dotnet build /warnaserror
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          bin/
          obj/
